name: Image Builder

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      # Trust our self-signed certificate
      - run: sudo mkdir -p /etc/docker/certs.d/registry.selfprivacy.org:5001
      - run: echo "$REGISTRY_SELFSIGNED_CERT" | sudo tee /etc/docker/certs.d/registry.selfprivacy.org:5001/ca.crt
        env:
          REGISTRY_SELFSIGNED_CERT: ${{ secrets.REGISTRY_SELFSIGNED_CERT }}
      # Login, build, and push
      - run: docker login registry.selfprivacy.org:5001 -u="$REGISTRY_USERNAME" -p="$REGISTRY_PASSWORD"
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      # Debug
      - run: docker pull ubuntu:latest
      - run: docker tag ubuntu:latest registry.selfprivacy.org:5001/ubuntu:latest
      - run: docker push registry.selfprivacy.org:5001/ubuntu:latest
      # - uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: "registry.selfprivacy.org:5001/flutter-build-env:latest"
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max