name: Image Builder

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      # Trust our self-signed certificate
      - run: echo "$REGISTRY_SELFSIGNED_CERT" | sudo tee /etc/ssl/certs/registry.crt
        env:
          REGISTRY_SELFSIGNED_CERT: ${{ secrets.REGISTRY_SELFSIGNED_CERT }}
      - run: sudo update-ca-certificates
      # Build, login, and push
      - run: docker build . --tag=localhost/flutter-build-env
      - run: docker login registry.selfprivacy.org:5001 -u="$REGISTRY_USERNAME" -p="REGISTRY_PASSWORD"
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      - run: docker push localhost/flutter-build-env docker://registry.selfprivacy.org:5001/flutter-build-env:latest