name: Image Builder

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      # Trust our self-signed certificate
      - run: echo "$REGISTRY_SELFSIGNED_CERT" | sudo tee /usr/local/share/ca-certificates/registry.crt
        env:
          REGISTRY_SELFSIGNED_CERT: ${{ secrets.REGISTRY_SELFSIGNED_CERT }}
      - run: sudo update-ca-certificates
      - run: sudo systemctl restart docker
      # Login, build, and push
      - run: docker login registry.selfprivacy.org:5001 -u="$REGISTRY_USERNAME" -p="$REGISTRY_PASSWORD"
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: "registry.selfprivacy.org:5001/flutter-build-env:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max