name: Image Builder

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '@daily'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build an Image
        run:
          - docker build .
