name: Flutter Build Environment Image

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Trust our self-signed certificate
      - run: sudo mkdir -p /etc/docker/certs.d/registry.selfprivacy.org:5001
      - run: echo "$REGISTRY_SELFSIGNED_CERT" | sudo tee /etc/docker/certs.d/registry.selfprivacy.org:5001/ca.crt
        env:
          REGISTRY_SELFSIGNED_CERT: ${{ secrets.REGISTRY_SELFSIGNED_CERT }}

      # Setup builder
      - uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [registry."registry.selfprivacy.org:5001"]
              ca=["/etc/docker/certs.d/registry.selfprivacy.org:5001/ca.crt"]

      # Login to our container registry
      - uses: docker/login-action@v2
        with:
          registry: registry.selfprivacy.org:5001
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and push image to the registry
      - uses: docker/build-push-action@v3
        with:
          context: flutter-build-env/
          push: true
          tags: "registry.selfprivacy.org:5001/flutter-build-env:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
